# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://dulanghai.com
date_format: "ordinal"
title: 码志
subtitle: "打码改变人生"
description: "王林的小房子"
keywords: 码志, Lin Wang, DULANGHAI
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Lin Wang
organization: 京颐集团
organization_url: http://www.kyeegroup.com/home.jsp
github_username: DULANGHAI
location: Shanghai, China
email: 604857875@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: DULANGHAI/DULANGHAI.github.io